/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arkueid_live2d_Live2D_LAppModel */

#ifndef _Included_com_arkueid_live2d_Live2D_LAppModel
#define _Included_com_arkueid_live2d_Live2D_LAppModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    createNativeObj
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_createNativeObj
  (JNIEnv *, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    destroyNativeObj
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_destroyNativeObj
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    loadModelJson
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_loadModelJson
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_draw
  (JNIEnv *, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    startMotion
 * Signature: (Ljava/lang/String;IILcom/arkueid/live2d/Live2D/LAppModel/OnStartMotionListener;Lcom/arkueid/live2d/Live2D/LAppModel/OnFinishMotionListener;)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_startMotion
  (JNIEnv *, jobject, jstring, jint, jint, jobject, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    startRandomMotion
 * Signature: (Ljava/lang/String;ILcom/arkueid/live2d/Live2D/LAppModel/OnStartMotionListener;Lcom/arkueid/live2d/Live2D/LAppModel/OnFinishMotionListener;)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_startRandomMotion
  (JNIEnv *, jobject, jstring, jint, jobject, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    setExpression
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_setExpression
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    setRandomExpression
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_setRandomExpression
  (JNIEnv *, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    hitTest
 * Signature: (FF)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_hitTest
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    hasMocConsistencyFromFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_hasMocConsistencyFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    touch
 * Signature: (FFLcom/arkueid/live2d/Live2D/LAppModel/OnStartMotionListener;Lcom/arkueid/live2d/Live2D/LAppModel/OnFinishMotionListener;)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_touch
  (JNIEnv *, jobject, jfloat, jfloat, jobject, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    drag
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_drag
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    isMotionFinished
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_isMotionFinished
  (JNIEnv *, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    setOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_setOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    setScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_setScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    setParameterValue
 * Signature: (Ljava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_setParameterValue
  (JNIEnv *, jobject, jstring, jfloat, jfloat);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    addParameterValue
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_addParameterValue
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_update
  (JNIEnv *, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    setAutoBreathEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_setAutoBreathEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    setAutoBlinkEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_setAutoBlinkEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    getParameterCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_getParameterCount
  (JNIEnv *, jobject);

/*
 * Class:     com_arkueid_live2d_Live2D_LAppModel
 * Method:    getParameter
 * Signature: (I)Lcom/arkueid/live2d/Live2D/Parameter;
 */
JNIEXPORT jobject JNICALL Java_com_arkueid_live2d_Live2D_00024LAppModel_getParameter
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
