/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arkueid_live2d_Live2D */

#ifndef _Included_com_arkueid_live2d_Live2D
#define _Included_com_arkueid_live2d_Live2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arkueid_live2d_Live2D
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_init
  (JNIEnv *, jclass);

/*
 * Class:     com_arkueid_live2d_Live2D
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_dispose
  (JNIEnv *, jclass);

/*
 * Class:     com_arkueid_live2d_Live2D
 * Method:    glewInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_glewInit
  (JNIEnv *, jclass);

/*
 * Class:     com_arkueid_live2d_Live2D
 * Method:    setGLProperties
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_setGLProperties
  (JNIEnv *, jclass);

/*
 * Class:     com_arkueid_live2d_Live2D
 * Method:    clearBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_clearBuffer
  (JNIEnv *, jclass);

/*
 * Class:     com_arkueid_live2d_Live2D
 * Method:    setLogEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_setLogEnable
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
