/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arkueid_live2d_Live2D_v3 */

#ifndef _Included_com_arkueid_live2d_Live2D_v3
#define _Included_com_arkueid_live2d_Live2D_v3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arkueid_live2d_Live2D_v3
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_1v3_init
  (JNIEnv *, jclass);

/*
 * Class:     com_arkueid_live2d_Live2D_v3
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_1v3_dispose
  (JNIEnv *, jclass);

/*
 * Class:     com_arkueid_live2d_Live2D_v3
 * Method:    clearBuffer
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_arkueid_live2d_Live2D_1v3_clearBuffer
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
